#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo "You must provide at least one Python version."
    exit 2
fi

echo "Configuring packages..."
sudo yum -y update -qq && sudo yum -y upgrade -qq
sudo yum -y install -qq \
    yum-utils \
    epel-release
sudo yum -y groupinstall "Development Tools"
sudo yum -y install -qq \
    bzip2-devel \
    cmake \
    db4-devel \
    gcc \
    gdbm-devel \
    libffi-devel \
    libpcap-devel \
    make \
    ncurses-devel \
    nss-devel \
    openssl11 \
    openssl11-devel \
    readline-devel \
    sqlite-devel \
    tk-devel \
    wget \
    xz-devel \
    zlib-devel

echo "configure openssl11 for Python3.11 onwards"
if [ -d /usr/local/openssl11 ]
then
    sudo rm -rf /usr/local/openssl11
fi
sudo mkdir -p /usr/local/openssl11
cd /usr/local/openssl11
sudo ln -s /usr/lib64/openssl11 lib
sudo ln -s /usr/include/openssl11 include
echo "done"

cd /tmp

for VER do
    if [[ $VER == *"a"* ]]; then
        PARTIAL="$(cut -d 'a' -f 1 <<< $VER)"
    elif [[ $VER == *"b"* ]]; then
        PARTIAL="$(cut -d 'b' -f 1 <<< $VER)"
    elif [[ $VER == *"rc"* ]]; then
        PARTIAL="$(cut -d 'r' -f 1 <<< $VER)"
    else
        PARTIAL=$VER
    fi

    echo "Downloading Python $VER..."
    wget -q https://www.python.org/ftp/python/$PARTIAL/Python-$VER.tgz

    if [[ ! -f Python-$VER.tgz ]]; then
        echo "That Python version does not exist."
        exit 2
    fi

    tar -xf Python-$VER.tgz

    echo "Building Python $VER..."
    cd Python-$VER
    ./configure -q --enable-optimizations --with-ensurepip=install --with-system-ffi
    make -s -j $(nproc)

    echo "Installing Python $VER..."
    sudo make -s altinstall
done

echo "All done!"
