#!/bin/bash

BIN_PATH=/usr/local/bin
LIB_PATH=/usr/local/lib

if [[ $# -eq 0 ]]; then
    echo "You must provide at least one Python version."
    exit 2
fi

echo "You are about to uninstall the following Python versions:
"
for VER do
    echo " * ${VER}"
done
read -p "
THIS ACTION IS IRREVERSIBLE. Are you sure you want to continue? (y/N): " confirm && [[ $confirm == [yY] ]] || exit 1

for VER do
    echo "Uninstalling Python $VER..."

    # Check if Python version exists.
    if [[ ! -f "${BIN_PATH}/python${VER}" ]]; then
        echo "That Python version is not installed, or you have supplied a patch version."
        exit 2
    fi

    # Remove files.
    sudo rm -rf "${BIN_PATH}/2to3-${VER}" \
        "${BIN_PATH}/idle${VER}" \
        "${BIN_PATH}/pip${VER}" \
        "${BIN_PATH}/pydoc${VER}" \
        "${BIN_PATH}/python${VER}" \
        "${BIN_PATH}/python${VER}-config" \
        "${LIB_PATH}/libpython${VER}.a" \
        "${LIB_PATH}/python${VER}" \
        "${LIB_PATH}/python${VER}-embed.pc" \
        "${LIB_PATH}/python${VER}.pc"
done

echo "All done!"
